<?php

namespace App\Services\Automation;

use App\Models\Customer;
use App\Models\JobOrder;
use App\Models\NotificationLog;
use App\Services\Notifications\Contracts\Notifier;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Spatie\Activitylog\Facades\CauserResolver;

class ActionRunner
{
    public function __construct(
        private readonly Notifier $notifier,
        private readonly Interpolator $interpolator,
    ) {}

    /** Run one action. Returns ['type'=>x, 'ok'=>bool, 'detail'=>...]. */
    public function run(array $action, array $context, Model $triggerModel, bool $dryRun = false): array
    {
        $type = $action['type'] ?? 'noop';

        try {
            $result = match ($type) {
                'send_sms'         => $this->runSendSms($action, $context, $dryRun),
                'update_field'     => $this->runUpdateField($action, $context, $triggerModel, $dryRun),
                'create_job_order' => $this->runCreateJobOrder($action, $context, $dryRun),
                'log_activity'     => $this->runLogActivity($action, $context, $dryRun),
                default            => ['ok' => false, 'detail' => "unknown action type: {$type}"],
            };
            return array_merge(['type' => $type], $result);
        } catch (\Throwable $e) {
            Log::error('ActionRunner::run threw', ['type' => $type, 'error' => $e->getMessage()]);
            return ['type' => $type, 'ok' => false, 'detail' => $e->getMessage()];
        }
    }

    private function runSendSms(array $action, array $context, bool $dryRun): array
    {
        $to   = $this->interpolator->render($action['to']   ?? '{{customer.phone}}', $context);
        $body = $this->interpolator->render($action['body'] ?? '', $context);

        if (! $to || ! $body) {
            return ['ok' => false, 'detail' => 'missing to or body after interpolation'];
        }
        if ($dryRun) {
            return ['ok' => true, 'detail' => "[dry-run] would SMS {$to}: {$body}"];
        }

        $customerId = data_get($context, 'customer.id');
        $log = NotificationLog::create([
            'channel' => 'sms', 'driver' => $this->notifier->id(),
            'to' => $to, 'body' => $body, 'event' => 'automation_rule',
            'customer_id' => $customerId, 'status' => 'queued',
        ]);
        $ref = $this->notifier->send($to, $body, ['source' => 'automation']);
        $log->update(['status' => 'sent', 'gateway_reference' => $ref, 'sent_at' => now()]);

        return ['ok' => true, 'detail' => "sent SMS to {$to}"];
    }

    private function runUpdateField(array $action, array $context, Model $triggerModel, bool $dryRun): array
    {
        $target = $action['target'] ?? null;       // e.g. 'subscription.status' or just 'status' (means trigger model)
        $value  = $this->interpolator->render((string) ($action['value'] ?? ''), $context);

        if (! $target) return ['ok' => false, 'detail' => 'missing target'];

        // resolve target: if "thismodel.field" or just "field", update the trigger model
        $parts = explode('.', $target);
        if (count($parts) === 1) {
            $field = $parts[0];
            if ($dryRun) return ['ok' => true, 'detail' => "[dry-run] would set trigger.{$field}={$value}"];
            $triggerModel->{$field} = $value;
            $triggerModel->save();
            return ['ok' => true, 'detail' => "set trigger.{$field}={$value}"];
        }

        // otherwise look up the related model via context (e.g. "customer.status")
        $relatedClass = $this->guessRelatedClass($parts[0]);
        $relatedId = data_get($context, $parts[0] . '.id');
        if (! $relatedClass || ! $relatedId) {
            return ['ok' => false, 'detail' => "cannot resolve {$parts[0]} for update"];
        }
        if ($dryRun) return ['ok' => true, 'detail' => "[dry-run] would set {$target}={$value}"];

        $related = $relatedClass::find($relatedId);
        if (! $related) return ['ok' => false, 'detail' => 'related record not found'];
        $related->{$parts[1]} = $value;
        $related->save();
        return ['ok' => true, 'detail' => "set {$target}={$value}"];
    }

    private function guessRelatedClass(string $key): ?string
    {
        return match ($key) {
            'customer'     => Customer::class,
            'subscription' => \App\Models\Subscription::class,
            'invoice'      => \App\Models\Invoice::class,
            'service'      => \App\Models\Service::class,
            default        => null,
        };
    }

    private function runCreateJobOrder(array $action, array $context, bool $dryRun): array
    {
        $description = $this->interpolator->render($action['description'] ?? 'Auto-generated by rule', $context);
        $type        = $action['job_type'] ?? 'repair';
        $priority    = $action['priority'] ?? 'normal';
        $customerId  = (int) $this->interpolator->render((string) ($action['customer_id'] ?? '{{customer.id}}'), $context);

        if ($dryRun) {
            return ['ok' => true, 'detail' => "[dry-run] would create JO type={$type} for customer #{$customerId}"];
        }

        $jo = JobOrder::create([
            'job_number'   => 'JO-AUTO-' . strtoupper(\Illuminate\Support\Str::random(6)),
            'type'         => $type,
            'priority'     => $priority,
            'status'       => 'pending',
            'customer_id'  => $customerId ?: null,
            'description'  => $description,
            'scheduled_at' => now()->addDay(),
        ]);
        return ['ok' => true, 'detail' => "JO #{$jo->id} created"];
    }

    private function runLogActivity(array $action, array $context, bool $dryRun): array
    {
        $description = $this->interpolator->render($action['description'] ?? 'automation', $context);
        if ($dryRun) return ['ok' => true, 'detail' => "[dry-run] would log: {$description}"];
        activity('automation')->log($description);
        return ['ok' => true, 'detail' => $description];
    }
}
